/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as News_detailsRouteImport } from './routes/news_details'
import { Route as News_insightsRouteImport } from './routes/news_insights'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const News_detailsRoute = News_detailsRouteImport.update({
  id: '/news_details',
  path: '/news_details',
  getParentRoute: () => rootRouteImport,
} as any)
const News_insightsRoute = News_insightsRouteImport.update({
  id: '/news_insights',
  path: '/news_insights',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/news_details': typeof News_detailsRoute
  '/news_insights': typeof News_insightsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/news_details': typeof News_detailsRoute
  '/news_insights': typeof News_insightsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/news_details': typeof News_detailsRoute
  '/news_insights': typeof News_insightsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/news_details' | '/news_insights'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/news_details' | '/news_insights'
  id: '__root__' | '/' | '/about' | '/news_details' | '/news_insights'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  News_detailsRoute: typeof News_detailsRoute
  News_insightsRoute: typeof News_insightsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news_details': {
      id: '/news_details'
      path: '/news_details'
      fullPath: '/news_details'
      preLoaderRoute: typeof News_detailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news_insights': {
      id: '/news_insights'
      path: '/news_insights'
      fullPath: '/news_insights'
      preLoaderRoute: typeof News_insightsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  News_detailsRoute: News_detailsRoute,
  News_insightsRoute: News_insightsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
